server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: video-server-challenge
  h2:
    console:
      enabled: true
gateway:
  regions:
    -
      url: http://localhost:8081
      name: europe
    -
      url: http://localhost:8082
      name: north-america
  endpoints:
    -
      path: '[/]api/user'
      method: GET
    -
      path: '[/]api/user/register'
      method: POST
    -
      path: '[/]api/user/.*/join-team'
      method: POST